# Generated by Django 4.1.3 on 2022-12-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_delete_websites'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(max_length=300)),
                ('postnummer', models.IntegerField(null=True)),
                ('gatenummer', models.IntegerField(null=True)),
                ('telia', models.BooleanField(default=False)),
                ('telenor', models.BooleanField(default=False)),
                ('altibox', models.BooleanField(default=False)),
                ('navn', models.CharField(max_length=100)),
                ('epost', models.CharField(max_length=100)),
                ('mobil_nummer', models.IntegerField()),
                ('contact_by_phone', models.BooleanField(blank=True)),
                ('contact_by_email', models.BooleanField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
    ]
