# Generated by Django 4.1.3 on 2022-12-10 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='gatenummer',
        ),
    ]
