# Generated by Django 4.1.3 on 2022-12-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_order_gatenummer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='gatenummer',
            field=models.IntegerField(null=True),
        ),
    ]
